# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Starbound-Fr | Communauté Francophone autour de Starbound
email: contact@starbound-fr.net
description: > # this means to ignore newlines until "baseurl:"
  Site francophone sur l'actualité autour de Starbound ! Communauté conviviale et accueillante !
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://starbound-fr.net" # the base hostname & protocol for your site
twitter_username: starbound_fr
github_username:  Starbound-Fr-net
permalink: /:title/

plugins: [jekyll-paginate]

# Pagination
paginate: 11
paginate_path: "/page/:num/"

# Themming Settings
layouts_dir:  ./_layouts/sb
includes_dir: ./_includes/sb
generic_cover: "/Assets/sb/images/generic_cover.png"
asset_path:
    root: "/Assets/sb/"
    images : "/Assets/sb/images"
    css: "/Assets/sb/css"
    js: "/Assets/sb/js"
    fonts: "/Assets/sb/fonts"
    uploads: "/Assets/uploads"

# Categories.rb config
category_title_prefix: 'Catégorie: '
category_dir: 'categories'
paginate_category_basepath: '/categories/:name/'
paginate_category_layout: 'category.html'
category_index_layout: 'categories-index.html'

# Tags.rb config
tag_title_prefix: 'Tags: '
tag_dir: 'tags'
paginate_tag_basepath: '/tags/:name/'
paginate_tag_layout: 'category.html'
tag_index_layout: 'tags-index.html'

# Authors.rb config
author_title_prefix: 'Rédacteur: '
author_dir: 'authors'
paginate_author_basepath: '/authors/:name/'
paginate_author_layout: 'author.html'
author_index_layout: 'authors-index.html'

# Contributors.rb config
contributor_title_prefix: 'Correcteur: '
contributor_dir: 'contributors'
paginate_contributor_basepath: '/contributors/:name/'
paginate_contributor_layout: 'author.html'
contributor_index_layout: 'contributors-index.html'

# Build settings
markdown: kramdown
encoding: utf-8

# routing
include: ['_pages', '404.html']
